'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

const statuses=['Submitted','Processing','Completed','Rejected'];
export default function AdminPage(){
 const [logged,setLogged]=useState(false); const [id,setId]=useState(''); const [password,setPassword]=useState(''); const [requests,setRequests]=useState<any[]>([]);
 function load(){const rows:any[]=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';if(k.startsWith('ads_')){try{rows.push(JSON.parse(localStorage.getItem(k)||''))}catch{}}}setRequests(rows.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))))}
 useEffect(()=>{if(sessionStorage.getItem('ads_admin')==='1'){setLogged(true);load();}},[]);
 function login(e:any){e.preventDefault();if(id==='admin'&&password==='admin123'){sessionStorage.setItem('ads_admin','1');setLogged(true);load()}else alert('Invalid admin ID or password');}
 function update(id:string,status:string){const raw=localStorage.getItem('ads_'+id);if(!raw)return;localStorage.setItem('ads_'+id,JSON.stringify({...JSON.parse(raw),status}));load();}
 if(!logged)return <main><header className="topbar"><div className="brand"><div className="logo">A</div><div><b>Aetasham Digital Seva</b><small>Admin Panel</small></div></div><nav><Link href="/">Home</Link><Link href="/services">Services</Link></nav></header><section className="section"><div className="formbox"><span className="eyebrow">ADMIN</span><h2>Admin Login</h2><form onSubmit={login}><label>Admin ID<input value={id} onChange={e=>setId(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary">Login</button></form><p className="note">Demo credentials currently used by this browser-only version: admin / admin123. Use a secure server-side login before production.</p></div></section></main>;
 const counts={total:requests.length,submitted:requests.filter(x=>x.status==='Submitted').length,processing:requests.filter(x=>x.status==='Processing').length,completed:requests.filter(x=>x.status==='Completed').length};
 return <main><header className="topbar"><div className="brand"><div className="logo">A</div><div><b>Aetasham Digital Seva</b><small>Admin Dashboard</small></div></div><nav><Link href="/">Home</Link><Link href="/services">Services</Link><button onClick={()=>{sessionStorage.removeItem('ads_admin');setLogged(false)}}>Logout</button></nav></header><section className="section"><div className="heading"><div><span className="eyebrow">ADMIN DASHBOARD</span><h2>Service Requests</h2></div><button className="primary" onClick={load}>Refresh</button></div><div className="grid"><article className="service"><h3>{counts.total}</h3><p>Total requests</p></article><article className="service"><h3>{counts.submitted}</h3><p>Submitted</p></article><article className="service"><h3>{counts.processing}</h3><p>Processing</p></article><article className="service"><h3>{counts.completed}</h3><p>Completed</p></article></div><div className="section" style={{padding:'35px 0'}}>{requests.length===0?<div className="notice"><div><b>No requests yet</b><p>Applications submitted in this same browser will appear here.</p></div></div>:requests.map(r=><article className="service" key={r.id} style={{marginBottom:12}}><h3>{r.service} · {r.id}</h3><p>Applicant: {r.name}<br/>Mobile: {r.mobile}<br/>{r.details||'No additional details'}</p><select value={r.status} onChange={e=>update(r.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></article>)}</div></section></main>;
}
