'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

const statuses = ['Submitted','Processing','Completed','Rejected'];
export default function AdminPage() {
  const [logged, setLogged] = useState(false); const [id, setId] = useState(''); const [password, setPassword] = useState(''); const [requests, setRequests] = useState<any[]>([]); const [error, setError] = useState('');
  async function load() { const response = await fetch('/api/admin/applications', { cache: 'no-store' }); if (!response.ok) { setLogged(false); return; } const data = await response.json(); setRequests(data.applications || []); setLogged(true); }
  useEffect(() => { void load(); }, []);
  async function login(e: any) { e.preventDefault(); setError(''); const response = await fetch('/api/admin/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, password }) }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Login failed.'); return; } setPassword(''); await load(); }
  async function updateStatus(appId: string, status: string) { const response = await fetch('/api/admin/status', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: appId, status }) }); if (!response.ok) { setError('Could not update status.'); return; } setRequests(rows => rows.map(r => r.id === appId ? { ...r, status } : r)); }
  async function logout() { await fetch('/api/admin/login', { method: 'DELETE' }); setLogged(false); setRequests([]); }

  if (!logged) return <main><header className="topbar"><div className="brand"><div className="logo">A</div><div><b>Aetasham Digital Seva</b><small>Admin Panel</small></div></div><nav><Link href="/">Home</Link><Link href="/services">Services</Link></nav></header><section className="section"><div className="formbox"><span className="eyebrow">ADMIN</span><h2>Admin Login</h2><form onSubmit={login}><label>Admin ID<input value={id} onChange={e=>setId(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary">Login</button></form>{error && <div className="notice"><div><b>{error}</b></div></div>}<p className="note">Admin credentials are checked on the server and are not stored in this page.</p></div></section></main>;

  const counts = { total: requests.length, submitted: requests.filter(x=>x.status==='Submitted').length, processing: requests.filter(x=>x.status==='Processing').length, completed: requests.filter(x=>x.status==='Completed').length };
  return <main><header className="topbar"><div className="brand"><div className="logo">A</div><div><b>Aetasham Digital Seva</b><small>Admin Dashboard</small></div></div><nav><Link href="/">Home</Link><Link href="/services">Services</Link><button onClick={logout}>Logout</button></nav></header><section className="section"><div className="heading"><div><span className="eyebrow">ADMIN DASHBOARD</span><h2>Service Requests</h2></div><button className="primary" onClick={load}>Refresh</button></div><div className="grid"><article className="service"><h3>{counts.total}</h3><p>Total requests</p></article><article className="service"><h3>{counts.submitted}</h3><p>Submitted</p></article><article className="service"><h3>{counts.processing}</h3><p>Processing</p></article><article className="service"><h3>{counts.completed}</h3><p>Completed</p></article></div><div className="section" style={{padding:'35px 0'}}>{requests.length===0?<div className="notice"><div><b>No requests yet</b><p>Applications submitted by customers will appear here.</p></div></div>:requests.map(r=><article className="service" key={r.id} style={{marginBottom:12}}><h3>{r.service} · {r.id}</h3><p>Applicant: {r.name}<br/>Mobile: {r.mobile}<br/>{r.details||'No additional details'}</p><select value={r.status} onChange={e=>updateStatus(r.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></article>)}</div></section></main>;
}
